name: Check and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1"
          prerelease: true
          title: "Development Build"
          files:
