name: Check and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
